// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfFvH1A2uST9YLtMa4EL5ktyp8jBLjB5M',
    appId: '1:117633376087:web:36d3685c784f7fbbfaa812',
    messagingSenderId: '117633376087',
    projectId: 'laporkades',
    authDomain: 'laporkades.firebaseapp.com',
    storageBucket: 'laporkades.firebasestorage.app',
    measurementId: 'G-KEK7JPBHSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCLn6rECF1pRkc5AEVlCpr1NzKYBcTLU',
    appId: '1:117633376087:android:947805c62b4afa17faa812',
    messagingSenderId: '117633376087',
    projectId: 'laporkades',
    storageBucket: 'laporkades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIGRBUZjhiUkQr2K0n2wNG9mrDdWkGgU',
    appId: '1:117633376087:ios:e28c9f78b16757defaa812',
    messagingSenderId: '117633376087',
    projectId: 'laporkades',
    storageBucket: 'laporkades.firebasestorage.app',
    iosBundleId: 'com.example.laporkadesApp',
  );
}
